# --------------------------------------------------------------------------------- #
# This is a template of verification configuration options for 6 hourly forecasts
# Copy this template to verif_config_6h.yml on the same folder and run verifcations
# --------------------------------------------------------------------------------- #

# PBS job related options, not required to reproduce results
qsub:
    qsub_loc: '/glade/u/home/ksha/CREDIT-arXiv/qsub/'
    scripts_loc: '/glade/u/home/ksha/CREDIT-arXiv/verification/scripts/'
    plot_data_loc: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/PLOT_data/'

# locations of bilinear interpolation weights and model grids
geo:
    geo_file_nc: '/glade/campaign/cisl/aiml/ksha/CREDIT/IFS_preprocess_param/ML_grid.nc'
    regrid_weights_numpy: '/glade/campaign/cisl/aiml/ksha/CREDIT/IFS_preprocess_param/griddata_weights.npy'

# locations and variable subsets for pre-processing ERA5 climatology from weatherbench2
ERA5_weatherbench:
    save_loc: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/VERIF/verif_6h/ERA5_clim/'
    save_loc_clim: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/VERIF/verif_6h/ERA5_clim/'
    year_range: [2018, 2022]
    verif_variables:
        geopotential: [500,]
        specific_humidity: [500,]
        temperature: [500,]
        u_component_of_wind: [500,]
        v_component_of_wind: [500,]
        surface_pressure: null
        2m_temperature: null
    rename_variables:
        geopotential: 'Z500'
        specific_humidity: 'Q500'
        temperature: 'T500'
        u_component_of_wind: 'U500'
        v_component_of_wind: 'V500'
        surface_pressure: 'SP'
        2m_temperature: 't2m'

# locations and variable subsets of the CREDIT N320 regular Gaussian grid ERA5 (target)
ERA5_ours:
    save_loc: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_arXiv/SixHourly_y*'
    save_loc_verif: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/VERIF/verif_6h/ERA5_clim/'
    year_range: [2019, 2023]
    verif_variables: 
        V500: null
        U500: null
        T500: null
        Q500: null
        Z500: null
        SP:  null
        t2m: null

# locations and variable subsets of the IFS data
IFS:
    save_loc: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/GATHER/IFS/'
    save_loc_gather: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/GATHER/IFS/'
    save_loc_verif: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/VERIF/verif_6h/IFS/'
    year_range: [2019, 2022]
    lead_range: [6, 240]
    verif_lead_range: [6, 240]
    verif_variables:
        geopotential: [500,]
        specific_humidity: [500,]
        temperature: [500,]
        u_component_of_wind: [500,]
        v_component_of_wind: [500,]
        surface_pressure: null
        2m_temperature: null
    rename_variables:
        geopotential: 'Z500'
        specific_humidity: 'Q500'
        temperature: 'T500'
        u_component_of_wind: 'U500'
        v_component_of_wind: 'V500'
        surface_pressure: 'SP'
        2m_temperature: 't2m'

# locations and variable subsets of the 6 hourly wxformer outputs
wxformer:
    save_loc_rollout: '/glade/derecho/scratch/ksha/CREDIT/RAW_OUTPUT/wxformer_6h/'
    save_loc_gather: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/GATHER/wxformer_6h/'
    save_loc_verif: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/VERIF/verif_6h/wxformer_6h/'
    year_range: [2019, 2022]
    lead_range: [6, 240]
    verif_lead_range: [6, 240]
    verif_variables: 
        V500: null
        U500: null
        T500: null
        Q500: null
        Z500: null
        SP:  null
        t2m: null
        
# locations and variable subsets of the 6 hourly fuxi outputs
fuxi:
    save_loc_rollout: '/glade/derecho/scratch/ksha/CREDIT/RAW_OUTPUT/fuxi_6h/'
    save_loc_gather: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/GATHER/fuxi_6h/'
    save_loc_verif: '/glade/campaign/cisl/aiml/ksha/CREDIT_arXiv/VERIF/verif_6h/fuxi_6h/'
    year_range: [2019, 2022]
    lead_range: [6, 240]
    verif_lead_range: [6, 240]
    verif_variables: 
        V500: null
        U500: null
        T500: null
        Q500: null
        Z500: null
        SP:  null
        t2m: null

        
        